-- DistrictsBuildings
-- Author: Bluehill
-- DateCreated: 2023-09-20 오후 7:46:52
--------------------------------------------------------------

UPDATE Districts SET PrereqCivic = 'CIVIC_POLITICAL_PHILOSOPHY' WHERE DistrictType = 'DISTRICT_GOVERNMENT';
UPDATE Districts SET PrereqTech = NULL, PrereqCivic = 'CIVIC_CIVIL_SERVICE' WHERE DistrictType = 'DISTRICT_DIPLOMATIC_QUARTER';
UPDATE Buildings SET PrereqTech = NULL, PrereqCivic = 'CIVIC_CIVIL_SERVICE' WHERE BuildingType = 'BUILDING_CONSULATE';
DELETE FROM DistrictModifiers WHERE DistrictType = 'DISTRICT_DIPLOMATIC_QUARTER' AND ModifierId = 'DIPLOMATIC_QUARTER_AWARD_ONE_INFLUENCE_TOKEN';
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES ('DIPLOMATIC_QUARTER_AWARD_TWO_INFLUENCE_TOKEN', 'MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN'), ('CONSULATE_AWARD_ONE_INFLUENCE_TOKEN', 'MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN'), ('CHANCERY_AWARD_ONE_INFLUENCE_TOKEN', 'MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DIPLOMATIC_QUARTER_AWARD_TWO_INFLUENCE_TOKEN', 'Amount', '2'), ('CONSULATE_AWARD_ONE_INFLUENCE_TOKEN', 'Amount', '1'),  ('CHANCERY_AWARD_ONE_INFLUENCE_TOKEN', 'Amount', '1');
INSERT INTO DistrictModifiers (DistrictType, ModifierId) VALUES ('DISTRICT_DIPLOMATIC_QUARTER', 'DIPLOMATIC_QUARTER_AWARD_TWO_INFLUENCE_TOKEN');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES ('BUILDING_CONSULATE', 'CONSULATE_AWARD_ONE_INFLUENCE_TOKEN'), ('BUILDING_CHANCERY', 'CHANCERY_AWARD_ONE_INFLUENCE_TOKEN');
