-- StartingUnits
-- Author: Bluehill
-- DateCreated: 2023-10-08 오후 12:27:17
--------------------------------------------------------------

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES ('TRAIT_LEADER_MAJOR_CIV', 'BUILDER_HUMAN_PLAYERS'), ('TRAIT_LEADER_MAJOR_CIV', 'SCOUT_HUMAN_PLAYERS');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES ('BUILDER_HUMAN_PLAYERS', 'MODIFIER_PLAYER_BUILT_CITIES_GRANT_FREE_UNIT', 'PLAYER_IS_HUMAN_AND_HAS_ONLY_ONE_CITY'),  ('SCOUT_HUMAN_PLAYERS', 'MODIFIER_PLAYER_BUILT_CITIES_GRANT_FREE_UNIT', 'PLAYER_IS_HUMAN_AND_HAS_ONLY_ONE_CITY');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES ('BUILDER_HUMAN_PLAYERS', 'UnitType', 'UNIT_BUILDER'), ('BUILDER_HUMAN_PLAYERS', 'Amount', 1), ('SCOUT_HUMAN_PLAYERS', 'UnitType', 'UNIT_SCOUT'), ('SCOUT_HUMAN_PLAYERS', 'Amount', 1);
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES ('PLAYER_IS_HUMAN_AND_HAS_ONLY_ONE_CITY', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES ('PLAYER_IS_HUMAN_AND_HAS_ONLY_ONE_CITY', 'REQUIRES_PLAYER_IS_HUMAN'), ('PLAYER_IS_HUMAN_AND_HAS_ONLY_ONE_CITY', 'REQUIRES_PLAYER_HAS_ONLY_ONE_CITY');
